# Generated by Django 6.0.6 on 2026-06-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_token_credit_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
