# Generated by Django 6.0.6 on 2026-06-14 15:17

import core.models.mergeset_file
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_project_to_mergeset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergesetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.mergeset_file.mergeset_file_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mergeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='core.mergeset')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
