# Generated by Django 6.0.6 on 2026-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mergesetfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergesetfile',
            name='delimiter',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='mergesetfile',
            name='headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mergesetfile',
            name='parse_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mergesetfile',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='mergesetfile',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mergesetfile',
            name='row_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
