# Generated by Django 6.0.6 on 2026-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mergesetfile_delimiter_mergesetfile_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergesetfile',
            name='sample_rows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
