# Generated by Django 6.0.6 on 2026-06-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mergesetfile_sample_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergePlanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('collecting_requirements', 'Collecting requirements'), ('mapping_ready', 'Mapping ready'), ('approved', 'Approved')], default='collecting_requirements', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mergeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_sessions', to='core.mergeset')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MergePlanningMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.mergeplanningsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MergePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved')], default='draft', max_length=16)),
                ('plan_json', models.JSONField(blank=True, default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mergeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_plans', to='core.mergeset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_plans', to='core.mergeplanningsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
