# Generated by Django 6.0.6 on 2026-07-05 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aiusagerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('average_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('provider', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'base_currency', 'quote_currency'],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'year', 'month'), name='unique_monthly_exchange_rate')],
            },
        ),
    ]
